learning_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views 

#Template Tagging
app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name = 'relative'),
    path('other/', views.other, name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    # path('other/', views.other, name = 'other'),
    # path('relative/', views.relative, name = 'relative'),
    path('basic_app/', include('basic_app.urls')) #universal url mapping 
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World','number':100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%url 'index'%}">BRAND</a></li>
                <li><a class="navbar-link" href="{%url 'admin:index'%}">ADMIN</a></li>
                <li><a class="navbar-link" href="{%url 'basic_app:other'%}">OTHER</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {%block body_block%}
        <!-- Anything outside of this will be inherited if you extend! -->
        {%endblock%}
    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
{%load my_extras%}
    {%block body_block%}
        
        <h1>WELCOME TO INDEX</h1>
        <h2>This is an example of template inheritance!</h2>
        <h1>{{text}}</h1>
        <h1>{{text|upper}}</h1>
        <h1>{{text|trim:'hello'}}</h1>
        <h1>{{number}}</h1>
        <h1>{{number|add:'99'}}</h1>
    {%endblock%}
    
    

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
    {%block body_block%}
        <h1>WELCOME TO OTHER</h1>
        <h2>This is an example of template inheritance!</h2>
    {%endblock%}
    
    

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{%url 'basic_app:other'%}">The Other Page</a>
    <a href="{%url 'admin:index'%}">The Admin Page</a>
    <a href="{%url 'index'%}">The Index Page</a>
</body>
</html>